### ISSUE TITLE
Small suggestion about app folder structure

### ISSUE THREAD

**Issue by abdulrahman19** [hassanzohdy/mongez#1]
First of all, thanks so much for the great effort you did.

The app folder structure is so awesome, but there is a small problem in my opinion. Imagine if you have a project with 30 or 50 models and of course their related classes on other folders.

navigate between those folders in current structure will be like a hell!

 I know you may feel about what I mean!

<pre>
Models
  └───
     ..User.php
     ..Post.php
     ..Product.php
     ..Shipping.php
     ......
Repositories
  └───
     ..UserRepository.php
     ..PostRepository.php
     ..ProductRepository.php
     ..ShippingRepository.php
     ......
 </pre>

Ok, you may say what the problem with that, you can use your editor to navigate easily between those files.

Yes,  you are right, but the problem not only in the navigation, sometimes you need to see the big picture of some modules, especially if you're a new team member, with current structure that will be so difficult.

My suggestion is adding a root folder for every module, and inside this module we can add all related folders. something like this:

<pre>
System
  └───
      Users
        └───
            Contracts
            Exceptions
            Models
            Repositories
            ......
      Posts
        └───
            Contracts
            Exceptions
            Models
            Repositories
            ......
</pre>

There's a wonderful article I think you would like to look at it [large scale Laravel application](https://medium.com/@munza/large-scale-laravel-application-9d52c3d38e51)

**Comment by hassanzohdy** [comment]
Thanks for the suggestion but we'll create much folders in that case.

And regarding the large applications, i do set each related models/repositories...etc in a proper folders.

```
Models
  └───
     Users
     └───
          Users.php
          ......
     Posts
     └───
          Posts.php
          ......
     ......
```

And so on.

In this case, we're mapping each `concept` together.

But unfortunately, your suggestion won't be fully optimized as laravel forces you to set your `Controllers` in the `Http` directory so it will break the chain here.

**Comment by abdulrahman19** [comment]
Yes, but even if Laravel forces me to add my `controllers` inside the `Http` directory , the `controllers` here will act just like APIs for outsourcing applications, all my core codes will stay inside modules folders.

I know there's not (a best practice) here, also I know this is way maybe not the best choice for some programmers :smile: but for me I need always to see the big picture :smiley:

Best wishes,,,

**Comment by hassanzohdy** [comment]
Actually, i'm using that approach that you're proposing in some of my applications.

It's quite good to be implemented.
For now, let's stick with the current file-system structure and see what improvements that we may do in the near future.

**Comment by falakjs** [comment]
This feature is now updated on the package.

**Comment by hassanzohdy** [comment]
That approach is now applied.

**Comment by hassanzohdy** [comment]
Closed due to completion.
